# Generated by Django 4.2.1 on 2023-05-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ipmodel_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
