# Generated by Django 4.2.1 on 2023-05-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description_week', models.TextField(null=True)),
                ('train1', models.TextField(null=True)),
                ('train2', models.TextField(null=True)),
                ('train3', models.TextField(null=True)),
                ('train4', models.TextField(null=True)),
                ('train5', models.TextField(null=True)),
                ('train6', models.TextField(null=True)),
                ('text_after_train', models.TextField(null=True)),
                ('slug', models.SlugField(max_length=130, null=True, unique=True, verbose_name='URL')),
                ('train_week', models.CharField(choices=[('1 неделя', 'First Week'), ('2 неделя', 'Second Week'), ('3 неделя', 'Third Week'), ('4 неделя', 'Fourth Week')], max_length=300)),
                ('train_day', models.CharField(choices=[('Понедельник', 'Monday'), ('Среда', 'Wednesday'), ('Пятница', 'Friday')], max_length=300)),
            ],
        ),
    ]
